import { Hono } from "hono";
import { adminRoutes } from "@routes/admin.routes";
import { employeeRoutes } from "@routes/employee.routes";
import { supplierRoutes } from "@routes/supplier.routes";
import { customerRoutes } from "@routes/customer.routes";
import { doctorRoutes } from "@routes/doctor.routes";
import { houseRoutes } from "@routes/house.routes";
import { itemRoutes } from "@routes/item.routes";
import { warehouseRoutes } from "@routes/warehouse.routes";
import { organizationRoutes, itemOrganizationRoutes } from "@routes/organization.routes";
import { stockUnitRoutes } from "@routes/stock-unit.routes";
import { assetRoutes } from "@routes/asset.routes";
import { batchRoutes } from "@routes/batch.routes";
import { batchHouseAllocationRoutes } from "@routes/batch-house-allocation.routes";
import { mortalityLogRoutes } from "@routes/mortality-log.routes";
import { batchHouseBalanceRoutes } from "@routes/batch-house-balance.routes";
import { purchaseRoutes, purchaseItemRoutes } from "@routes/purchase.routes";
import { stockLedgerRoutes } from "@routes/stock-ledger.routes";
import { inventoryAdjustmentRoutes } from "@routes/inventory-adjustment.routes";
import { consumptionRoutes } from "@routes/consumption.routes";
import { medicationRoutes } from "@routes/medication.routes";
import { vaccinationRoutes } from "@routes/vaccination.routes";
import { environmentRecordRoutes } from "@routes/environment-record.routes";
import { weightRecordRoutes } from "@routes/weight-record.routes";
import { batchFeedingProgramRoutes } from "@routes/batch-feeding-program.routes";
import { saleRoutes } from "@routes/sale.routes";
import { birdSaleRoutes } from "@routes/bird-sale.routes";
import { paymentInstrumentRoutes } from "@routes/payment-instrument.routes";
import { paymentRoutes } from "@routes/payment.routes";
import { expenseRoutes } from "@routes/expense.routes";
import { assetDepreciationRoutes } from "@routes/asset-depreciation.routes";
import { performanceScoreEntryRoutes } from "@routes/performance-score-entry.routes";
import { payrollRecordRoutes } from "@routes/payroll-record.routes";
import { alertRoutes } from "@routes/alert.routes";
import { auditLogRoutes } from "@routes/audit-log.routes";

export const appRoutes = new Hono();

appRoutes.route("/admins", adminRoutes);
appRoutes.route("/employees", employeeRoutes);
appRoutes.route("/suppliers", supplierRoutes);
appRoutes.route("/customers", customerRoutes);
appRoutes.route("/doctors", doctorRoutes);
appRoutes.route("/houses", houseRoutes);
appRoutes.route("/items", itemRoutes);
appRoutes.route("/warehouses", warehouseRoutes);
appRoutes.route("/organizations", organizationRoutes);
appRoutes.route("/item-organizations", itemOrganizationRoutes);
appRoutes.route("/stock-units", stockUnitRoutes);
appRoutes.route("/assets", assetRoutes);
appRoutes.route("/batches", batchRoutes);
appRoutes.route("/batch-house-allocations", batchHouseAllocationRoutes);
appRoutes.route("/mortality-logs", mortalityLogRoutes);
appRoutes.route("/batch-house-balances", batchHouseBalanceRoutes);
appRoutes.route("/purchases", purchaseRoutes);
appRoutes.route("/purchase-items", purchaseItemRoutes);
appRoutes.route("/stock-ledger", stockLedgerRoutes);
appRoutes.route("/inventory-adjustments", inventoryAdjustmentRoutes);
appRoutes.route("/consumptions", consumptionRoutes);
appRoutes.route("/medications", medicationRoutes);
appRoutes.route("/vaccinations", vaccinationRoutes);
appRoutes.route("/environment-records", environmentRecordRoutes);
appRoutes.route("/weight-records", weightRecordRoutes);
appRoutes.route("/batch-feeding-programs", batchFeedingProgramRoutes);
appRoutes.route("/sales", saleRoutes);
appRoutes.route("/bird-sales", birdSaleRoutes);
appRoutes.route("/payment-instruments", paymentInstrumentRoutes);
appRoutes.route("/payments", paymentRoutes);
appRoutes.route("/expenses", expenseRoutes);
appRoutes.route("/asset-depreciations", assetDepreciationRoutes);
appRoutes.route("/performance-score-entries", performanceScoreEntryRoutes);
appRoutes.route("/payroll-records", payrollRecordRoutes);
appRoutes.route("/alerts", alertRoutes);
appRoutes.route("/audit-logs", auditLogRoutes);
