import { Hono } from "hono";
import { adminRoutes } from "@routes/admin.routes";
import { employeeRoutes } from "@routes/employee.routes";
import { supplierRoutes } from "@routes/supplier.routes";
import { customerRoutes } from "@routes/customer.routes";
import { doctorRoutes } from "@routes/doctor.routes";
import { houseRoutes } from "@routes/house.routes";
import { itemRoutes } from "@routes/item.routes";
import { warehouseRoutes } from "@routes/warehouse.routes";
import { organizationRoutes, itemOrganizationRoutes } from "@routes/organization.routes";
import { stockUnitRoutes } from "@routes/stock-unit.routes";
import { assetRoutes } from "@routes/asset.routes";
import { batchRoutes } from "@routes/batch.routes";
import { batchHouseAllocationRoutes } from "@routes/batch-house-allocation.routes";
import { mortalityLogRoutes } from "@routes/mortality-log.routes";
import { batchHouseBalanceRoutes } from "@routes/batch-house-balance.routes";
import { purchaseRoutes, purchaseItemRoutes } from "@routes/purchase.routes";

export const appRoutes = new Hono();

appRoutes.route("/admins", adminRoutes);
appRoutes.route("/employees", employeeRoutes);
appRoutes.route("/suppliers", supplierRoutes);
appRoutes.route("/customers", customerRoutes);
appRoutes.route("/doctors", doctorRoutes);
appRoutes.route("/houses", houseRoutes);
appRoutes.route("/items", itemRoutes);
appRoutes.route("/warehouses", warehouseRoutes);
appRoutes.route("/organizations", organizationRoutes);
appRoutes.route("/item-organizations", itemOrganizationRoutes);
appRoutes.route("/stock-units", stockUnitRoutes);
appRoutes.route("/assets", assetRoutes);
appRoutes.route("/batches", batchRoutes);
appRoutes.route("/batch-house-allocations", batchHouseAllocationRoutes);
appRoutes.route("/mortality-logs", mortalityLogRoutes);
appRoutes.route("/batch-house-balances", batchHouseBalanceRoutes);
appRoutes.route("/purchases", purchaseRoutes);
appRoutes.route("/purchase-items", purchaseItemRoutes);
