import prisma from "@lib/db";
import { Prisma } from "../../prisma/generated/prisma/client";
import { AppError } from "@lib/app-error";
import { handlePrismaWriteError } from "@lib/prisma-errors";
import { toSkipTake, buildMeta } from "@lib/pagination";
import type { CreateAlertInput, ListAlertsQuery } from "@validators/alert.validator";
import { getItemBalances } from "@lib/stock-balance";
import {
    AUDIENCE,
    TASK_OVERDUE_GRACE_HOURS,
    farmDayStart,
    monthKey,
    mortalityLevel,
    overdueByHours,
    overdueLabel,
    pastDailyCutoff,
} from "@lib/alert-rules";
import { farmDay } from "@lib/farm-day";
import type { AuthContext } from "../types/app";

const EXPIRY_WARNING_DAYS = 30;
const PAYROLL_DUE_CUTOFF_DAY = 5; // flag if last month's payroll isn't generated by the 5th
const NEGATIVE_PATTERN_THRESHOLD = -5; // net points this month
const PROBATION_WARNING_DAYS = 7; // warn this far ahead of a probation ending
const PAYOUT_WARNING_DAY = 5; // warn from this day of the month; pay is due by the 7th working day

type AlertDraft = {
    type: "EMPLOYEE" | "BATCH" | "FEED" | "MEDICINE" | "SYSTEM";
    level: "INFO" | "WARNING" | "CRITICAL";
    title: string;
    description?: string;
    related_id?: string;
    /** Employee roles that also see it; admins always do. See AUDIENCE. */
    audience: readonly string[];
    /** The condition this alert is about, e.g. "NEG_PERF:<employee id>". One ACTIVE alert per key. */
    key: string;
};

/** One ACTIVE alert per condition (its `key`) at a time -- reconciling twice in a row shouldn't
 * spam duplicates, and two different conditions about the same employee mustn't hide each other.
 * An alert already on file is refreshed in place (its numbers and level move as the condition does),
 * and resolved automatically once a scan no longer raises its key -- see `resolveCleared`.
 * The partial unique index on dedupe_key is what makes this race-free (overlapping scans, a manual
 * scan during the timer): the loser's insert fails and it returns the winner's row. */
async function upsertActiveAlert(draft: AlertDraft) {
    const fields = {
        title: draft.title,
        type: draft.type,
        level: draft.level,
        description: draft.description ?? null,
        audience: [...draft.audience],
    };
    const existing = await prisma.alerts.findFirst({
        where: { dedupe_key: draft.key, status: "ACTIVE" },
    });
    if (existing) {
        const same =
            existing.title === fields.title &&
            existing.level === fields.level &&
            existing.description === fields.description &&
            existing.audience.join() === fields.audience.join();
        return same ? existing : prisma.alerts.update({ where: { id: existing.id }, data: fields });
    }
    try {
        return await prisma.alerts.create({
            data: {
                ...fields,
                dedupe_key: draft.key,
                issued_at: new Date(),
                // Server-side scan, not a client retry -- the dedupe above is what
                // keeps repeat scans from spamming, so this just satisfies the column.
                idempotency_key: crypto.randomUUID(),
                ...(draft.related_id !== undefined && { related_id: draft.related_id }),
            },
        });
    } catch (err) {
        // A concurrent scan raised the same condition between our check and insert.
        if (err instanceof Prisma.PrismaClientKnownRequestError && err.code === "P2002") {
            return prisma.alerts.findFirst({ where: { dedupe_key: draft.key, status: "ACTIVE" } });
        }
        throw err;
    }
}

/** Each check returns the keys it raised this run, so the scan can resolve the rest of its family. */
type Raised = Set<string>;

async function raise(raised: Raised, draft: AlertDraft) {
    await upsertActiveAlert(draft);
    raised.add(draft.key);
}

async function checkLowStock(): Promise<Raised> {
    const raised: Raised = new Set();
    const items = await prisma.item.findMany({
        where: { is_active: true, reorder_level: { not: null } },
    });
    const balances = await getItemBalances(items.map((i) => i.id));
    for (const item of items) {
        const balance = balances.get(item.id) ?? new Prisma.Decimal(0);
        if (balance.lessThan(item.reorder_level!)) {
            // ponytail: this string is a live FK code (ItemCategory.code) a user can rename via Settings,
            // which silently breaks this comparison with no error -- needs a stable-key mechanism if this keeps mattering.
            const type =
                item.category === "MEDICINE" || item.category === "VACCINE" ? "MEDICINE" : "FEED";
            const empty = balance.lessThanOrEqualTo(0);
            await raise(raised, {
                type,
                level: empty ? "CRITICAL" : "WARNING",
                title: empty
                    ? `${item.name} is out of stock`
                    : `${item.name} is below reorder level`,
                description: `Current balance ${balance.toString()}, reorder level ${item.reorder_level!.toString()}`,
                related_id: item.id,
                audience: AUDIENCE.MANAGER,
                key: `LOW_STOCK:${item.id}`,
            });
        }
    }
    return raised;
}

/** Per house, so the person in the shed knows which one to look at. */
async function checkMortalitySpikes(): Promise<Raised> {
    const raised: Raised = new Set();
    const since = new Date(Date.now() - 24 * 60 * 60 * 1000);
    const [balances, deaths] = await Promise.all([
        prisma.batchHouseBalance.findMany({
            where: { quantity: { gt: 0 }, batch: { status: "RUNNING" } },
            include: { house: true, batch: true },
        }),
        prisma.mortalityLog.groupBy({
            by: ["batch_id", "house_id"],
            where: { date: { gte: since } },
            _sum: { count_died: true },
        }),
    ]);
    const diedBy = new Map(
        deaths.map((d) => [`${d.batch_id}:${d.house_id}`, d._sum.count_died ?? 0]),
    );
    for (const b of balances) {
        const died = diedBy.get(`${b.batch_id}:${b.house_id}`) ?? 0;
        const rate = died / b.quantity;
        const level = mortalityLevel(rate);
        if (!level) continue;
        await raise(raised, {
            type: "BATCH",
            level,
            title: `${b.house.name}: mortality ${(rate * 100).toFixed(1)}% in the last 24h`,
            description: `${died} of ${b.quantity} live birds (${b.batch.batch_code})`,
            related_id: b.house_id,
            audience: AUDIENCE.FIELD,
            key: `MORTALITY:${b.batch_id}:${b.house_id}`,
        });
    }
    return raised;
}

async function checkExpiringStock(): Promise<Raised> {
    const raised: Raised = new Set();
    const soonThreshold = new Date(Date.now() + EXPIRY_WARNING_DAYS * 24 * 60 * 60 * 1000);
    const expiringLots = await prisma.purchaseItem.findMany({
        where: { expiration_date: { lte: soonThreshold, gte: new Date() } },
        include: { item: true },
    });
    for (const lot of expiringLots) {
        await raise(raised, {
            type: "MEDICINE",
            level: "WARNING",
            title: `${lot.item.name} lot expires ${lot.expiration_date!.toISOString().slice(0, 10)}`,
            related_id: lot.id,
            audience: AUDIENCE.MANAGER,
            key: `EXPIRY:${lot.id}`,
        });
    }
    return raised;
}

const lastMonthStart = (now: Date) =>
    new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() - 1, 1));
const plural = (n: number, word: string) => `${n} ${word}${n === 1 ? "" : "s"}`;

/** One alert for the whole month, not one per employee -- twenty identical rows are noise. Admin only. */
async function checkPayrollDue(): Promise<Raised> {
    const raised: Raised = new Set();
    const now = new Date();
    if (now.getUTCDate() < PAYROLL_DUE_CUTOFF_DAY) return raised;

    const month = lastMonthStart(now);
    const missing = await prisma.employees.count({
        where: { profile: { is_active: true }, payrollRecords: { none: { month } } },
    });
    if (missing > 0) {
        await raise(raised, {
            type: "EMPLOYEE",
            level: "INFO",
            title: `Payroll not yet generated for ${plural(missing, "employee")}`,
            description: `Month: ${monthKey(month)}`,
            audience: AUDIENCE.ADMIN,
            key: `PAYROLL_DUE:${monthKey(month)}`,
        });
    }
    return raised;
}

async function checkNegativePerformancePatterns(): Promise<Raised> {
    const raised: Raised = new Set();
    const now = new Date();
    const monthStart = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1));
    const employees = await prisma.employees.findMany({ include: { profile: true } });
    for (const employee of employees) {
        if (!employee.profile.is_active) continue;
        const entries = await prisma.performanceScoreEntry.findMany({
            // Bucketed by when it happened, and only settled entries: a disputed
            // or voided entry shouldn't raise a pattern warning.
            where: {
                employee_id: employee.id,
                status: "ACTIVE",
                incident_date: { gte: monthStart },
            },
        });
        const sum = entries.reduce((total, entry) => total + entry.points, 0);
        if (sum <= NEGATIVE_PATTERN_THRESHOLD) {
            // About a person, so a manager's alert -- never a co-worker's.
            await raise(raised, {
                type: "EMPLOYEE",
                level: "WARNING",
                title: `${employee.profile.name} has a negative performance pattern this month`,
                description: `Net ${sum} points so far`,
                related_id: employee.id,
                audience: AUDIENCE.MANAGER,
                key: `NEG_PERF:${employee.id}`,
            });
        }
    }
    return raised;
}

/**
 * Probation doesn't end by itself -- someone has to issue the offer confirmation
 * and move the employee to CONFIRMED. This raises the reminder a week out, and
 * escalates once the date has passed and nothing happened.
 */
async function checkProbationEnding(): Promise<Raised> {
    const raised: Raised = new Set();
    const now = new Date();
    const horizon = new Date(now.getTime() + PROBATION_WARNING_DAYS * 86_400_000);

    const employees = await prisma.employees.findMany({
        where: {
            employment_status: "PROBATION",
            probation_end_date: { not: null, lte: horizon },
        },
        include: { profile: true },
    });

    for (const employee of employees) {
        if (!employee.profile.is_active) continue;
        const endsAt = employee.probation_end_date!;
        const overdue = endsAt < now;
        await raise(raised, {
            type: "EMPLOYEE",
            level: overdue ? "WARNING" : "INFO",
            title: overdue
                ? `${employee.profile.name}'s probation ended -- confirm or terminate`
                : `${employee.profile.name}'s probation ends soon`,
            description: `Probation end: ${endsAt.toISOString().slice(0, 10)}`,
            related_id: employee.id,
            audience: AUDIENCE.MANAGER,
            key: `PROBATION:${employee.id}`,
        });
    }
    return raised;
}

/**
 * Wages are due by the 7th working day after month end, so the warning goes up
 * on day 5 -- late enough not to nag, early enough to still act on. Two alerts
 * for the month, not one per person: failed payouts (Critical, money didn't move)
 * and wages still unpaid or pending. Admin only.
 */
async function checkPayoutDue(): Promise<Raised> {
    const raised: Raised = new Set();
    const now = new Date();
    if (now.getUTCDate() < PAYOUT_WARNING_DAY) return raised;

    const month = lastMonthStart(now);
    const records = await prisma.payrollRecord.findMany({
        where: { month },
        include: { payout: true },
    });
    const failed = records.filter((r) => r.payout?.status === "FAILED").length;
    const unpaid = records.filter(
        (r) => r.payout?.status !== "CONFIRMED" && r.payout?.status !== "FAILED",
    ).length;

    if (failed > 0) {
        await raise(raised, {
            type: "EMPLOYEE",
            level: "CRITICAL",
            title: `${plural(failed, "payout")} failed for ${monthKey(month)}`,
            description: "The money did not reach the employee. Retry or fix the payout account.",
            audience: AUDIENCE.ADMIN,
            key: `PAYOUT_FAILED:${monthKey(month)}`,
        });
    }
    if (unpaid > 0) {
        await raise(raised, {
            type: "EMPLOYEE",
            level: "WARNING",
            title: `${plural(unpaid, "wage")} for ${monthKey(month)} not paid yet`,
            description: "Due by the 7th working day.",
            audience: AUDIENCE.ADMIN,
            key: `PAYOUT_DUE:${monthKey(month)}`,
        });
    }
    return raised;
}

/** A running house with no feed entry by the evening cut-off. Clears when it is logged, and the key
 *  carries the date so tomorrow starts fresh. */
async function checkDailyLogs(): Promise<Raised> {
    const raised: Raised = new Set();
    const now = new Date();
    if (!pastDailyCutoff(now)) return raised;

    const since = farmDayStart(now);
    const day = farmDay(now).toISOString().slice(0, 10);
    const [balances, feed] = await Promise.all([
        prisma.batchHouseBalance.findMany({
            where: { quantity: { gt: 0 }, batch: { status: "RUNNING" } },
            include: { house: true },
        }),
        prisma.consumption.groupBy({
            by: ["house_id"],
            where: { date: { gte: since }, item: { category: "FEED" } },
        }),
    ]);
    const hasFeed = new Set(feed.map((f) => f.house_id));
    for (const b of balances) {
        if (hasFeed.has(b.house_id)) continue;
        await raise(raised, {
            type: "BATCH",
            level: "WARNING",
            title: `${b.house.name}: no feed logged today`,
            description: "No feed entry has been recorded for this house today.",
            related_id: b.house_id,
            audience: AUDIENCE.FIELD,
            key: `LOG_MISSING:${b.house_id}:${day}`,
        });
    }
    return raised;
}

/** For the manager: a task still pending well past its due time. The worker sees it on their own Tasks tab. */
async function checkOverdueTasks(): Promise<Raised> {
    const raised: Raised = new Set();
    const now = new Date();
    const cutoff = new Date(now.getTime() - TASK_OVERDUE_GRACE_HOURS * 3_600_000);
    const tasks = await prisma.employeeTaskAssignment.findMany({
        where: { status: "PENDING", due_at: { lt: cutoff } },
        include: { employee: { include: { profile: true } } },
    });
    for (const t of tasks) {
        await raise(raised, {
            type: "EMPLOYEE",
            level: "WARNING",
            title: `${t.employee.profile.name}: "${t.title}" is overdue`,
            description: `${overdueLabel(overdueByHours(t.due_at, now))} past its due time`,
            related_id: t.id,
            audience: AUDIENCE.MANAGER,
            key: `TASK_OVERDUE:${t.id}`,
        });
    }
    return raised;
}

/** Every alert family the scan owns: its key prefix and the check that raises it. A family whose
 *  check threw is left alone -- better a stale alert than resolving what we couldn't verify. */
const FAMILIES: [prefix: string, check: () => Promise<Raised>][] = [
    ["LOW_STOCK:", checkLowStock],
    ["MORTALITY:", checkMortalitySpikes],
    ["EXPIRY:", checkExpiringStock],
    ["PAYROLL_DUE:", checkPayrollDue],
    ["NEG_PERF:", checkNegativePerformancePatterns],
    ["PROBATION:", checkProbationEnding],
    ["PAYOUT_FAILED:", checkPayoutDue],
    ["PAYOUT_DUE:", checkPayoutDue],
    ["LOG_MISSING:", checkDailyLogs],
    ["TASK_OVERDUE:", checkOverdueTasks],
];

/** Resolves ACTIVE alerts in a family that this scan no longer raised: the stock came in, the reading
 *  went back to normal, the task got done. Alerts a person raised by hand have no key and are untouched. */
async function resolveCleared(prefix: string, stillRaised: Raised) {
    await prisma.alerts.updateMany({
        where: {
            status: "ACTIVE",
            dedupe_key: { startsWith: prefix, notIn: [...stillRaised] },
        },
        data: { status: "RESOLVED", resolved_at: new Date() },
    });
}

/** Admins see every alert; an employee sees those whose audience names their role. */
function visibleTo(auth: AuthContext | undefined): Prisma.AlertsWhereInput {
    if (!auth || auth.role === "ADMIN") return {};
    return { audience: { has: auth.employee_role ?? "" } };
}

export const AlertService = {
    async getAll(query: ListAlertsQuery, auth?: AuthContext) {
        const where: Prisma.AlertsWhereInput = {
            ...visibleTo(auth),
            ...(query.type !== undefined && { type: query.type }),
            ...(query.level !== undefined && { level: query.level }),
            ...(query.status !== undefined && { status: query.status }),
        };
        const [alerts, total] = await Promise.all([
            prisma.alerts.findMany({
                where,
                orderBy: { created_at: "desc" },
                ...toSkipTake(query),
            }),
            prisma.alerts.count({ where }),
        ]);
        return { alerts, meta: buildMeta(total, query) };
    },

    async getById(id: string, auth?: AuthContext) {
        const alert = await prisma.alerts.findFirst({ where: { id, ...visibleTo(auth) } });
        if (!alert) throw AppError.notFound("Alert");
        return alert;
    },

    /** Wrapped since idempotency_key gained a unique constraint: a replayed
     *  offline write must surface as a 409 naming the field, which is how the
     *  field app's outbox tells "already landed" from a real failure. Leaking
     *  the raw P2002 as a 500 would read as transient and retry forever. */
    async create(data: CreateAlertInput) {
        try {
            return await prisma.alerts.create({
                data: {
                    title: data.title,
                    type: data.type,
                    level: data.level,
                    issued_at: new Date(),
                    idempotency_key: data.idempotency_key ?? crypto.randomUUID(),
                    // Raised by hand (a manager flagging stock): a manager's alert, and the admin's.
                    audience: [...AUDIENCE.MANAGER],
                    ...(data.description !== undefined && { description: data.description }),
                    ...(data.related_id !== undefined && { related_id: data.related_id }),
                    ...(data.action_type !== undefined && { action_type: data.action_type }),
                },
            });
        } catch (err) {
            return handlePrismaWriteError(err);
        }
    },

    /** Closes the active alert about one condition right now, instead of waiting for the next scan: a task
     *  that was just cancelled or finished should not keep showing as overdue. A no-op when there is none. */
    async resolveByKey(key: string) {
        await prisma.alerts.updateMany({
            where: { dedupe_key: key, status: "ACTIVE" },
            data: { status: "RESOLVED", resolved_at: new Date() },
        });
    },

    /** A manager can only resolve what they can see: an admin-only payroll alert is not theirs to clear. */
    async resolve(id: string, auth?: AuthContext) {
        const alert = await prisma.alerts.findFirst({ where: { id, ...visibleTo(auth) } });
        if (!alert) throw AppError.notFound("Alert");
        if (alert.status === "RESOLVED") throw AppError.conflict("Alert is already resolved");
        return prisma.alerts.update({
            where: { id },
            data: { status: "RESOLVED", resolved_at: new Date() },
        });
    },

    /** Reconciles current state against every alert family above: raises what is true, refreshes what
     * changed, and resolves what no longer is. Runs hourly (alert-scan-loop) or on demand -- not a live
     * hook on every write, which would mean instrumenting every service for the same eventual outcome. */
    async runScan() {
        // PAYOUT_FAILED and PAYOUT_DUE share one check: run each distinct check once.
        const checks = [...new Set(FAMILIES.map(([, check]) => check))];
        const results = new Map(
            await Promise.all(
                checks.map(async (check) => {
                    try {
                        return [check, await check()] as const;
                    } catch (err) {
                        console.error("[alerts] check failed", err);
                        return [check, null] as const;
                    }
                }),
            ),
        );
        for (const [prefix, check] of FAMILIES) {
            const raised = results.get(check);
            if (raised) await resolveCleared(prefix, raised);
        }
        return this.getAll({ page: 1, limit: 100, status: "ACTIVE" });
    },
};
