import prisma from "@lib/db";
import { Prisma } from "../../prisma/generated/prisma/client";
import { AppError } from "@lib/app-error";
import { toSkipTake, buildMeta } from "@lib/pagination";
import type { CreateAlertInput, ListAlertsQuery } from "@validators/alert.validator";
import { getItemBalances } from "@lib/stock-balance";

const MORTALITY_RATE_THRESHOLD = 0.01; // 1% of a house's live birds dying in 24h
const EXPIRY_WARNING_DAYS = 30;
const PAYROLL_DUE_CUTOFF_DAY = 5; // flag if last month's payroll isn't generated by the 5th
const NEGATIVE_PATTERN_THRESHOLD = -5; // net points this month

type AlertDraft = {
    type: "EMPLOYEE" | "BATCH" | "FEED" | "MEDICINE" | "SYSTEM";
    level: "INFO" | "WARNING" | "CRITICAL";
    title: string;
    description?: string;
    related_id?: string;
};

/** One ACTIVE alert per (type, related_id) at a time -- reconciling twice
 * in a row shouldn't spam duplicates. Resolving it lets the next scan
 * re-raise if the condition is still true. */
async function upsertActiveAlert(draft: AlertDraft) {
    if (draft.related_id) {
        const existing = await prisma.alerts.findFirst({
            where: { type: draft.type, related_id: draft.related_id, status: "ACTIVE" },
        });
        if (existing) return existing;
    }
    return prisma.alerts.create({
        data: {
            title: draft.title,
            type: draft.type,
            level: draft.level,
            issued_at: new Date(),
            ...(draft.description !== undefined && { description: draft.description }),
            ...(draft.related_id !== undefined && { related_id: draft.related_id }),
        },
    });
}

async function checkLowStock() {
    const items = await prisma.item.findMany({
        where: { is_active: true, reorder_level: { not: null } },
    });
    const balances = await getItemBalances(items.map((i) => i.id));
    for (const item of items) {
        const balance = balances.get(item.id) ?? new Prisma.Decimal(0);
        if (balance.lessThan(item.reorder_level!)) {
            // ponytail: this string is a live FK code (ItemCategory.code) a user can rename via Settings,
            // which silently breaks this comparison with no error -- needs a stable-key mechanism if this keeps mattering.
            const type =
                item.category === "MEDICINE" || item.category === "VACCINE" ? "MEDICINE" : "FEED";
            await upsertActiveAlert({
                type,
                level: "WARNING",
                title: `${item.name} is below reorder level`,
                description: `Current balance ${balance.toString()}, reorder level ${item.reorder_level!.toString()}`,
                related_id: item.id,
            });
        }
    }
}

async function checkMortalitySpikes() {
    const runningBatches = await prisma.batches.findMany({
        where: { status: "RUNNING" },
        include: { houseBalances: true },
    });
    const since = new Date(Date.now() - 24 * 60 * 60 * 1000);
    for (const batch of runningBatches) {
        const liveCount = batch.houseBalances.reduce((sum, b) => sum + b.quantity, 0);
        if (liveCount === 0) continue;

        const deaths = await prisma.mortalityLog.aggregate({
            where: { batch_id: batch.id, date: { gte: since } },
            _sum: { count_died: true },
        });
        const died = deaths._sum.count_died ?? 0;
        const rate = died / liveCount;
        if (rate > MORTALITY_RATE_THRESHOLD) {
            await upsertActiveAlert({
                type: "BATCH",
                level: "CRITICAL",
                title: `${batch.batch_code} mortality rate ${(rate * 100).toFixed(1)}% in the last 24h`,
                description: `${died} of ${liveCount} live birds`,
                related_id: batch.id,
            });
        }
    }
}

async function checkExpiringStock() {
    const soonThreshold = new Date(Date.now() + EXPIRY_WARNING_DAYS * 24 * 60 * 60 * 1000);
    const expiringLots = await prisma.purchaseItem.findMany({
        where: { expiration_date: { lte: soonThreshold, gte: new Date() } },
        include: { item: true },
    });
    for (const lot of expiringLots) {
        await upsertActiveAlert({
            type: "MEDICINE",
            level: "WARNING",
            title: `${lot.item.name} lot expires ${lot.expiration_date!.toISOString().slice(0, 10)}`,
            related_id: lot.id,
        });
    }
}

async function checkPayrollDue() {
    const now = new Date();
    if (now.getUTCDate() < PAYROLL_DUE_CUTOFF_DAY) return;

    const lastMonthStart = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() - 1, 1));
    const employees = await prisma.employees.findMany({ include: { profile: true } });
    for (const employee of employees) {
        if (!employee.profile.is_active) continue;
        const existing = await prisma.payrollRecord.findUnique({
            where: { employee_id_month: { employee_id: employee.id, month: lastMonthStart } },
        });
        if (!existing) {
            await upsertActiveAlert({
                type: "EMPLOYEE",
                level: "INFO",
                title: `Payroll not yet generated for ${employee.profile.name}`,
                description: `Month: ${lastMonthStart.toISOString().slice(0, 7)}`,
                related_id: employee.id,
            });
        }
    }
}

async function checkNegativePerformancePatterns() {
    const now = new Date();
    const monthStart = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1));
    const employees = await prisma.employees.findMany({ include: { profile: true } });
    for (const employee of employees) {
        if (!employee.profile.is_active) continue;
        const entries = await prisma.performanceScoreEntry.findMany({
            where: { employee_id: employee.id, date: { gte: monthStart } },
        });
        const sum = entries.reduce((total, entry) => total + entry.points, 0);
        if (sum <= NEGATIVE_PATTERN_THRESHOLD) {
            await upsertActiveAlert({
                type: "EMPLOYEE",
                level: "WARNING",
                title: `${employee.profile.name} has a negative performance pattern this month`,
                description: `Net ${sum} points so far`,
                related_id: employee.id,
            });
        }
    }
}

export const AlertService = {
    async getAll(query: ListAlertsQuery) {
        const where = {
            ...(query.type !== undefined && { type: query.type }),
            ...(query.level !== undefined && { level: query.level }),
            ...(query.status !== undefined && { status: query.status }),
        };
        const [alerts, total] = await Promise.all([
            prisma.alerts.findMany({
                where,
                orderBy: { created_at: "desc" },
                ...toSkipTake(query),
            }),
            prisma.alerts.count({ where }),
        ]);
        return { alerts, meta: buildMeta(total, query) };
    },

    async getById(id: string) {
        const alert = await prisma.alerts.findUnique({ where: { id } });
        if (!alert) throw AppError.notFound("Alert");
        return alert;
    },

    async create(data: CreateAlertInput) {
        return prisma.alerts.create({
            data: {
                title: data.title,
                type: data.type,
                level: data.level,
                issued_at: new Date(),
                ...(data.description !== undefined && { description: data.description }),
                ...(data.related_id !== undefined && { related_id: data.related_id }),
                ...(data.action_type !== undefined && { action_type: data.action_type }),
            },
        });
    },

    async resolve(id: string) {
        const alert = await prisma.alerts.findUnique({ where: { id } });
        if (!alert) throw AppError.notFound("Alert");
        if (alert.status === "RESOLVED") throw AppError.conflict("Alert is already resolved");
        return prisma.alerts.update({
            where: { id },
            data: { status: "RESOLVED", resolved_at: new Date() },
        });
    },

    /** Reconciles current state against all 5 trigger conditions from
     * FEATURES.md §2.13 and raises/dedupes ACTIVE alerts accordingly. Meant
     * to run periodically (a cron, once one exists) or on demand -- not a
     * live hook on every write, which would mean instrumenting eight
     * already-built services for the same eventual outcome. */
    async runScan() {
        await Promise.all([
            checkLowStock(),
            checkMortalitySpikes(),
            checkExpiringStock(),
            checkPayrollDue(),
            checkNegativePerformancePatterns(),
        ]);
        return this.getAll({ page: 1, limit: 100, status: "ACTIVE" });
    },
};
