const ENV = {
    PORT: process.env.PORT || 4000,
    API_VERSION: process.env.API_VERSION || "v1",
    CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
    SUPPLIER_CLOUDINARY_UPLOAD_PRESET:
        process.env.SUPPLIER_CLOUDINARY_UPLOAD_PRESET,
    CLOUDINARY_UPLOAD_PRESET_BASE: process.env.CLOUDINARY_UPLOAD_PRESET_BASE,
    CUSTOMER_CLOUDINARY_UPLOAD_PRESET:
        process.env.CUSTOMER_CLOUDINARY_UPLOAD_PRESET,
    ADMIN_CLOUDINARY_UPLOAD_PRESET: process.env.ADMIN_CLOUDINARY_UPLOAD_PRESET,
    DOCTOR_CLOUDINARY_UPLOAD_PRESET:
        process.env.DOCTOR_CLOUDINARY_UPLOAD_PRESET,
    PHARMACHIST_CLOUDINARY_UPLOAD_PRESET:
        process.env.PHARMACHIST_CLOUDINARY_UPLOAD_PRESET,
    EMPLOYEE_CLOUDINARY_UPLOAD_PRESET:
        process.env.EMPLOYEE_CLOUDINARY_UPLOAD_PRESET,
    TEMP_CLOUDINARY_UPLOAD_PRESET: process.env.TEMP_CLOUDINARY_UPLOAD_PRESET || "temp",
};

export { ENV };
